services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
    command: server /data --console-address :9001
    volumes:
      - ./minio-data:/data
    stdin_open: true
    tty: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set myminio http://localhost:9000 admin password;
      mc mb myminio/warehouse;
      tail -f /dev/null"
    networks:
      lakehouse-network:

  postgres-nessie:
    image: postgres:12
    container_name: postgres-nessie
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nessie
      POSTGRES_PASSWORD: nessie
      POSTGRES_DB: nessie
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      lakehouse-network:

  postgres-airflow:
    image: postgres:12
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres_airflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      lakehouse-network:

  airflow-init:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    image: airflow-base
    container_name: airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create \
        --username airflow \
        --password airflow \
        --firstname Admin \
        --lastname User \
        --role Admin \
        --email airflow@example.com &&
        airflow connections add 'spark_default' --conn-type 'spark' \
        --conn-host 'spark://spark-master:7077'
      "
    depends_on:
      postgres-airflow:
        condition: service_healthy
    networks:
      lakehouse-network:

  airflow-webserver:
    image: airflow-base
    container_name: airflow-webserver
    ports:
      - "8081:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/logs:/opt/airflow/logs
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      lakehouse-network:

  airflow-scheduler:
    image: airflow-base
    container_name: airflow-scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/plugins:/opt/airflow/plugins
      - ./airflow/logs:/opt/airflow/logs
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      lakehouse-network:

  nessie:
    image: projectnessie/nessie:0.75.0
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      - NESSIE_VERSION_STORE_TYPE=jdbc
      - NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE=postgresql
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres:5432/nessie
      - QUARKUS_DATASOURCE_USERNAME=nessie
      - QUARKUS_DATASOURCE_PASSWORD=nessie
      - NESSIE_SERVER_AUTHENTICATION_ENABLED=false
    depends_on:
      postgres-nessie:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./nessie-data:/nessie/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:19120/api/v1/config || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      lakehouse-network:
    
  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:25.1
    container_name: dremio
    ports:
      - "9047:9047"
      - "31010:31010"
      - "32010:32010"
    volumes:
      - ./dremio-data:/opt/dremio/data
    restart: always
    networks:
      lakehouse-network:

  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    depends_on:
      minio:
        condition: service_healthy
      postgres-nessie:
        condition: service_healthy
      airflow-webserver:
        condition: service_healthy
      nessie:
        condition: service_healthy
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      AWS_REGION: us-east-1
    restart: always
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./scripts:/opt/bitnami/spark/scripts
    networks:
      lakehouse-network:

  spark-worker:
    image: bitnami/spark:3.5.1
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 2G
      SPARK_DRIVER_MEMORY: 2G
      SPARK_EXECUTOR_MEMORY: 2G
    restart: always
    networks:
      lakehouse-network:

networks:
  lakehouse-network:
