services:
  minio:
    image: minio/minio:RELEASE.2025-02-18T16-25-55Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
      MINIO_REGION_NAME: us-east-1
      MINIO_REGION: us-east-1
    command: server /data --console-address :9001
    volumes:
      - ./minio-data:/data
    stdin_open: true
    tty: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: >
      /bin/sh -c "
      minio server /data --console-address ':9001' &
      sleep 5;
      mc alias set myminio http://localhost:9000 admin password;
      mc mb myminio/warehouse;
      tail -f /dev/null"
    networks:
      lakehouse-network:

  postgres-nessie:
    image: postgres:12
    container_name: postgres-nessie
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: nessie
      POSTGRES_PASSWORD: nessie
      POSTGRES_DB: nessie
    volumes:
      - ./postgres-nessie-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      lakehouse-network:

  postgres-airflow:
    image: postgres:12
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres-airflow-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      lakehouse-network:
    
  airflow-init:
    build:
      context: ./airflow
      dockerfile: Dockerfile
    image: airflow-base
    container_name: airflow-init
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username airflow --password password --firstname Airflow --lastname Nguyen --role Admin --email airflow@example.com &&
        airflow connections add 'spark_default' --conn-type 'spark' --conn-host 'spark://spark-master:7077'
      "
    depends_on:
      postgres-airflow:
        condition: service_healthy
    networks:
      lakehouse-network:

  airflow-webserver:
    image: airflow-base
    container_name: airflow-webserver
    environment:
      LOAD_EX: n
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: 47b37ccabffe201db14ebe15cd84b5b2d8a36ef54a0933af9ac3b820ad998e81
      AIRFLOW__CORE__FERNET_KEY: 0usUZ-xg86LwdICflo01YbDGVdxwObwwwSuGZJQkysI=
    ports:
      - "9090:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./models:/opt/models 
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9090/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      lakehouse-network:

  airflow-scheduler:
    image: airflow-base
    container_name: airflow-scheduler
    environment:
      LOAD_EX: n
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: 47b37ccabffe201db14ebe15cd84b5b2d8a36ef54a0933af9ac3b820ad998e81
      AIRFLOW__CORE__FERNET_KEY: 0usUZ-xg86LwdICflo01YbDGVdxwObwwwSuGZJQkysI=
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./models:/opt/models 
    command: scheduler
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      lakehouse-network:

  nessie:
    image: projectnessie/nessie:0.75.0
    container_name: nessie
    ports:
      - "19120:19120"
    environment:
      NESSIE_VERSION_STORE_TYPE: jdbc
      NESSIE_VERSION_STORE_PERSIST_JDBC_DATASOURCE: postgresql
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres-nessie:5432/nessie"
      QUARKUS_DATASOURCE_USERNAME: "nessie"
      QUARKUS_DATASOURCE_PASSWORD: "nessie"
      NESSIE_SERVER_AUTHENTICATION_ENABLED: false
    depends_on:
      postgres-nessie:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./nessie-data:/nessie/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:19120/api/v1/config || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      lakehouse-network:

  dremio:
    platform: linux/x86_64
    image: dremio/dremio-oss:25.1
    container_name: dremio
    ports:
      - "9047:9047"
      - "31010:31010" 
      - "32010:32010"
    volumes:
      - ./dremio/dremio-data:/opt/dremio/data
      - ./dremio/dremio.conf:/opt/dremio/conf/dremio.conf
      - ./dremio/core-site.xml:/opt/dremio/conf/core-site.xml
    networks:
      lakehouse-network:
  
  spark-master:
    image: bitnamilegacy/spark:3.5.4
    container_name: spark-master
    ports:
      - "8088:8080"
      - "7077:7077"
    environment:
      SPARK_MODE: master
      SPARK_MASTER_HOST: spark-master
      SPARK_MASTER_PORT: 7077
      AWS_REGION: us-east-1
    volumes:
      - ./spark/spark-defaults.conf:/opt/bitnami/spark/conf/spark-defaults.conf
      - ./scripts:/opt/bitnami/spark/scripts
      - ./models:/opt/models 
    networks:
      lakehouse-network:

  spark-worker:
    image: bitnamilegacy/spark:3.5.4
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
      SPARK_WORKER_CORES: 1
      SPARK_WORKER_MEMORY: 2G
      SPARK_DRIVER_MEMORY: 2G
      SPARK_EXECUTOR_MEMORY: 2G
    volumes:
      - ./models:/opt/models
    networks:
      lakehouse-network:
  
  jupyter:
    image: quay.io/jupyter/pyspark-notebook:spark-3.5.3
    container_name: jupyter
    restart: always
    ports:
      - "8386:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/notebooks
      - ./models:/opt/models 
    networks:
      lakehouse-network:

  postgres-superset:
    image: postgres:12
    container_name: postgres-superset
    environment:
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
      POSTGRES_DB: superset
    volumes:
      - ./postgres-superset-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      lakehouse-network:
  
  superset-init:
    image: apache/superset:3.0.4
    container_name: superset-init
    depends_on:
      postgres-superset:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: -c "
      set -e;
      superset db upgrade;
      superset fab create-admin \
        --username admin \
        --firstname Admin \
        --lastname User \
        --email admin@superset.com \
        --password admin || true;
      superset db upgrade;
      superset init;"
    environment:
      SUPERSET_ENV: production
      SUPERSET_CONFIG_PATH: /app/superset_config.py
    volumes:
      - ./superset/superset_config.py:/app/superset_config.py
    networks:
      lakehouse-network:

  superset:
    image: apache/superset:3.0.4
    container_name: superset
    depends_on:
      - postgres-superset
      - superset-init
    environment:
      SUPERSET_ENV: production
      SUPERSET_CONFIG_PATH: /app/superset_config.py
    volumes:
      - ./superset/superset-data:/app/superset_home
      - ./superset/superset_config.py:/app/superset_config.py
    command: -c "pip install sqlalchemy-dremio pyarrow"
    ports:
      - "8236:8088"
    networks:
      lakehouse-network:

networks:
  lakehouse-network: